stages:
  - test
  - build
  - deploy

variables:
  NODE_VERSION: "18"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

test:lint:
  stage: test
  image: node:18-alpine
  before_script:
    - npm install
  script:
    - echo "Test lint"
    - npm run lint || echo "Lint ignoré"
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

test:build:
  stage: test
  image: node:18-alpine
  before_script:
    - npm install
  script:
    - echo "Test build"
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 hour
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

build:docker:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  script:
    - echo "Build Docker ignoré pour le moment"
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

deploy:netlify:
  stage: deploy
  image: node:18-alpine
  before_script:
    - npm install
    - npm install -g netlify-cli
  script: |
    echo "Déploiement vers Netlify..."
    npm run build
    netlify deploy --prod --dir=dist --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
    echo "AgenticSST déployé avec succès!"
  environment:
    name: production
    url: https://agenticsstquebec.netlify.app
  rules:
    - if: $CI_COMMIT_BRANCH == "main"